# Nome da aplicação
spring.application.name=photo-archive

# Configuração do Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/photoarchive_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA / Hibernate
# "update" cria as tabelas automaticamente para nós baseando-se no código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# Configurações de Segurança (JWT)
# ==============================================================
# Em produção, esta chave DEVE ser uma string muito complexa e guardada em variáveis de ambiente.
# Esta é uma chave hexadecimal de 256 bits gerada para o nosso ambiente de desenvolvimento.
photoarchive.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Tempo de expiração do token em milissegundos (86400000 ms = 24 horas)
photoarchive.app.jwtExpirationMs=86400000